require File.dirname(__FILE__) + '/metafun/ivar'
require File.dirname(__FILE__) + '/metafun/selfclass'
require File.dirname(__FILE__) + '/metafun/eigenclass'
require File.dirname(__FILE__) + '/metafun/aliasing'
require File.dirname(__FILE__) + '/metafun/namespace'
require File.dirname(__FILE__) + '/metafun/annotations'
require File.dirname(__FILE__) + '/metafun/auto_annotations'
require File.dirname(__FILE__) + '/metafun/rename'
